.TH LILO 8
.SH NAME
lilo \- Installer for m68k boot loader
.SH SYNOPSIS
.B lilo
ARGS MISSING!
.SH DESCRIPTION
MISSING!
.SH OPTIONS
MISSING!
.SH FILES
.TP
.I /etc/lilo.conf
.TP
.I /boot/loader
.TP
.I /boot/loader.patched
.SH AUTHORS
Geert Uytterhoeven <Geert.Uytterhoeven@cs.kuleuven.ac.be>,
Roman Hodek <Roman.Hodek@informatik.uni-erlangen.de>,
Andreas Schwab <schwab@issan.informatik.uni-dortmund.de>,
Arjan Knor, Robert de Vries
